### ISSUE TITLE
MLE subcommand usage question

### ISSUE THREAD

**Issue by YichaoOU** [WubingZhang/MAGeCKFlute#1]
Following the nature protocols paper, I have two conditions: A & B, and the Day 0 info. I want to compare A & B. I made the design matrix like Table 5. 

When I got the mle results, it basically gave me two beta values; namely A vs. Day 0 and B vs. Day 0, right? 

What if I just want a beta value for A vs. B? Is it appropriate to treat B as Day 0 and then the design matrix will just have A and B?

Thanks,
Yichao

**Comment by jinyanyouyu1994** [comment]
How to deal with the paired-end fastq file?
my code is :mageck count -l library_mageck.csv -n s2 --sample-label NC85_T1,NC85_T2,NC85_96_R1,NC85_96_R2 --fastq 85-T1_combined_R1.fastq.gz,85-T1_combined_R2.fastq.gz 85-T2_combined_R1.fastq.gz,85-T2_combined_R2.fastq.gz 85-96-R1_combined_R1.fastq.gz,85-96-R1_combined_R2.fastq.gz 85-96-R2_combined_R1.fastq.gz,85-96-R2_combined_R2.fastq.gz
when I try to use the --fastq-2, there is an error:  mageck count: error: one of the arguments --fastq -k/--count-table is required. I don't understand the count-table?

**Comment by WubingZhang** [comment]
Hi,

> Following the nature protocols paper, I have two conditions: A & B, and the Day 0 info. I want to compare A & B. I made the design matrix like Table 5.
> 
> When I got the mle results, it basically gave me two beta values; namely A vs. Day 0 and B vs. Day 0, right?
> 
> What if I just want a beta value for A vs. B? Is it appropriate to treat B as Day 0 and then the design matrix will just have A and B?
> 
> Thanks,
> Yichao

Hi,

You can make a design matrix like below:

Day0 1 0 0
A       1 1 0
B       1 1 1

**Comment by WubingZhang** [comment]
> How to deal with the paired-end fastq file?
> my code is :mageck count -l library_mageck.csv -n s2 --sample-label NC85_T1,NC85_T2,NC85_96_R1,NC85_96_R2 --fastq 85-T1_combined_R1.fastq.gz,85-T1_combined_R2.fastq.gz 85-T2_combined_R1.fastq.gz,85-T2_combined_R2.fastq.gz 85-96-R1_combined_R1.fastq.gz,85-96-R1_combined_R2.fastq.gz 85-96-R2_combined_R1.fastq.gz,85-96-R2_combined_R2.fastq.gz
> when I try to use the --fastq-2, there is an error: mageck count: error: one of the arguments --fastq -k/--count-table is required. I don't understand the count-table?


Hi, 

Could you post this question in google group (https://groups.google.com/forum/#!forum/mageck) so that Wei can deal with it?

Thanks1

**Comment by Yongli-Qi** [comment]
> Hi,
> 
> > Following the nature protocols paper, I have two conditions: A & B, and the Day 0 info. I want to compare A & B. I made the design matrix like Table 5.
> > When I got the mle results, it basically gave me two beta values; namely A vs. Day 0 and B vs. Day 0, right?
> > What if I just want a beta value for A vs. B? Is it appropriate to treat B as Day 0 and then the design matrix will just have A and B?
> > Thanks,
> > Yichao
> 
> Hi,
> 
> You can make a design matrix like below:
> 
> Day0 1 0 0 A 1 1 0 B 1 1 1

Hi. Could you explain the column names of the matrix, please? Thank you :)
