### ISSUE TITLE
Why does BatchRemove calculate a logarithm of base e?

### ISSUE THREAD

**Issue by eregenyi** [WubingZhang/MAGeCKFlute#2]
Hi Zhang,

I was experimenting with the batch effect removal functionality of mageck flute, and looked at the source code to understand better what was going on. I saw that in MAGeCKFlute/R/BatchRemove.R, line 46, the log transformation is log(dt+1). log() by default computes a logarithm of base _e_, for a log2 the base has to be specified like log(dt + 1, 2). 
Was base _e_ the intention (I am asking because of the log2trans variable implied to me that it is log2)? What is the advantage of log _e_ is over log2? 

Best,

**Comment by WubingZhang** [comment]
Hi Eregenyi,

I would say that's a bug. In terms of batch effect removal, I think it's complicated and I'm not sure what's the difference between using log2 and log.

Thanks!
